all: sample1 sample2 sample3 sample4 dbg_read
sample1: sample1.c 
	gcc -g -Wall $< -l cdio -o $@
sample2: sample2.c 
	gcc -g -Wall $< -l cdio -o $@

sample3: sample3.c 
	gcc -g -Wall $< -l cdio -o $@

sample4: sample4.c 
	gcc -g -Wall $< -l cdio -o $@

