name: Windows, MinGW

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: >-
          mingw-w64-${{ matrix.env }}-toolchain
          base-devel
          autotools
          help2man
    - name: Build
      run: |
        ./autogen.sh
        make -j4
    - name: Test
      run: make check
