name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: sudo apt-get install -y help2man
      - name: Build
        run: |
          set -x
          ./autogen.sh
          make V=1
      - name: Run tests
        run: make check
