name: Windows, VS2022

on: [push, pull_request]

env:
  SOLUTION_FILE_PATH: ./libcdio.sln

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        TARGET_PLATFORM: [x86, x64]
        BUILD_CONFIGURATION: [Debug, Release]

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    - name: Build
      shell: cmd
      run: msbuild ${{ env.SOLUTION_FILE_PATH }} /m /p:Configuration=${{ matrix.BUILD_CONFIGURATION }},Platform=${{ matrix.TARGET_PLATFORM }}
